[package]
name = "evtap"
version = "0.1.0-rc.1"
authors = ["Maximilian Schmidt <maximilian@schmidt.so>"]
edition = "2024"
rust-version = "1.92"
description = "A local-first Linux keyboard mechanics analyzer"
repository = "https://github.com/schmidma/evtap"
homepage = "https://github.com/schmidma/evtap"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["typing", "keyboard", "evdev", "analytics"]
categories = ["visualization"]
publish = false

[dependencies]
camino = "1.2.5"
color-eyre = "0.6.5"
eframe = { version = "0.35.0", default-features = false, features = [
  "accesskit",
  "default_fonts",
  "glow",
  "wayland",
  "x11",
] }
evdev = { version = "0.13.2", features = ["tokio"] }
tokio = { version = "1.53.1", features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "sync",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
xkbcommon = "0.9.0"

[profile.release]
lto = "thin"
strip = "symbols"
